### ISSUE TITLE
Atualizar Backlog do produto

### ISSUE THREAD

**Issue by Michel-Momose** [CoderhoodFatec-2024-1/Coderhood#24]

**Comment by Michel-Momose** [comment]
Atualizar backlog de acordo com o andamento atual do projeto.

Cabeçalho com logo. Ok

Links para acesso rápido. OK

Integrantes. OK

Descrição do Desafio. NOk

Objetivo. NOk

Requisitos Funcionais. Ok

Requisitos Não Funcionais. OK

Cronograma. NOK

Product BackLog NOK

Tecnologias Utilizadas - NOK

**Comment by cesarpelogia** [comment]
Backlog atualizado conforme validação do cliente.
