### ISSUE TITLE
Gerenciamento estação

### ISSUE THREAD

**Issue by MateusMSoares** [CoderhoodFatec-2024-1/Coderhood#33]
Regras de negócio:
O número da estação não pode se repetir no banco.

- [x] Desenvolver classes e ordem para solução do problema.
- [x] Criar tela.
- [x] Apresentar para o time
- [x] Criar funcionalidades visando as regras de negócio.
- [x] Testar

**Comment by cesarpelogia** [comment]
Taks finalizada com ressalvas. Cliente questionou alguns pontos pós apresentação, que foram corrigidos.
